FROM node:18-alpine AS build

WORKDIR /usr/web/ismile

COPY . .

# Using Corepack
RUN corepack enable && corepack install

RUN yarn install

RUN yarn build

CMD [ "yarn", "preview", "--host", "0.0.0.0" ]
