name: Publish Latest Image to Docker Hub

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - Dockerfile.preview

env:
  IMAGE_TAG: web

jobs:
  Push-Latest:
    name: Build and Push Ismile-Web Latest Production Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Jakarta"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push to Docker Hub
        run: |
          DATE_TAG=${{ env.IMAGE_TAG }}-$(date +'%Y.%m.%d-%H.%M.%S')
          docker build \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/ismile-website:${{ env.IMAGE_TAG }} \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/ismile-website:$DATE_TAG \
            --push .

